version: '3'
services:
  consul-server-1:
    image: consul:latest
    ports:
      - "8500:8500"
      - "8600:8600"
    volumes:
      - ./server.json:/consul/config/server.json

  consul-server-2:
    image: consul:latest
    volumes:
      - ./server.json:/consul/config/server.json

  consul-server-3:
    image: consul:latest
    volumes:
      - ./server.json:/consul/config/server.json

  service-a:
    build: service-a/
    ports:
      - "80:80"
    volumes:
      - ./service-a/consul:/consul/config
    depends_on: 
      - "consul-server-1"
      - "consul-server-2"
      - "consul-server-3"

  service-b:
    build: service-b/
    ports:
      - "8788:8788"
    volumes:
      - ./service-b/consul:/consul/config
    depends_on: 
      - "consul-server-1"
      - "consul-server-2"
      - "consul-server-3"

  service-c:
    build: service-c/
    ports:
      - "8791:8791"
    volumes:
      - ./service-c/consul:/consul/config
    depends_on: 
      - "consul-server-1"
      - "consul-server-2"
      - "consul-server-3"
