version: '3'
services:
  consul-server:
    image: consul:latest
    ports:
      - "8500:8500"
      - "8600:8600"
    volumes:
      - ./server.json:/consul/config/server.json

  service-b:
    build: service-b/
    ports:
      - "8788:8788"
    volumes:
      - ./service-b/consul:/consul/config
