version: '3'
services:
  consul_server:
    image: consul:latest
    ports:
      - "8500:8500"
      - "8600:8600"
    volumes:
      - ./server.json:/consul/config/server.json

  service_a:
    build: service_a/
    ports:
      - "80:80"
    volumes:
      - ./service_a/consul:/consul/config
