version: '3'
services:
  consul_server:
    image: consul:latest
    ports:
      - "8500:8500"
      - "8600:8600"

  service_a:
    build: service_a/
    ports:
      - "80:80"
    volumes:
      - ./service_a/consul:/consul/config

  service_b:
    build: service_b/
    ports:
      - "8788:8788"
    volumes:
      - ./service_a/consul:/consul/config

  service_c:
    build: service_c/
    ports:
      - "8791:8791"
    volumes:
      - ./service_a/consul:/consul/config
