version: '3'
services:
  gateway:
    build: gateway/
    ports:
      - "80:80"
    depends_on: 
      - "consul-server-1"
      - "consul-server-2"
      - "consul-server-3"
  consul-server-1:
    image: consul:latest
    ports:
      - "8500:8500"
      - "8600:8600"
    volumes:
      - ./consul-server/server.json:/consul/config/server.json
    command: "consul agent -config-dir=/consul/config/ -node=consul-server-1"

  consul-server-2:
    image: consul:latest
    volumes:
      - ./consul-server/server.json:/consul/config/server.json
    command: "consul agent -config-dir=/consul/config/ -node=consul-server-2"

  consul-server-3:
    image: consul:latest
    volumes:
      - ./consul-server/server.json:/consul/config/server.json
    command: "consul agent -config-dir=/consul/config/ -node=consul-server-3"

  service-a:
    build: service-a/
    ports:
    volumes:
      - ./service-a/consul:/consul/config
    depends_on: 
      - "consul-server-1"
      - "consul-server-2"
      - "consul-server-3"

  service-b:
    build: service-b/
    volumes:
      - ./service-b/consul:/consul/config
    depends_on: 
      - "consul-server-1"
      - "consul-server-2"
      - "consul-server-3"

  service-c:
    build: service-c/
    volumes:
      - ./service-c/consul:/consul/config
    depends_on: 
      - "consul-server-1"
      - "consul-server-2"
      - "consul-server-3"
